name: hello-world-flow
on: [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.13.0'
      - run: npm install
      - run: ls -la